# Generated by Django 3.0.6 on 2020-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(),
        ),
    ]
